### PR TITLE
Add markdown render, code  highlight and code copy button

### PR DESCRIPTION
**Pull request by yueqing-wolai**
image

### CODE REVIEW

**Comment by wong2** [comment]
This looks ugly, can we improve the UI?

**Comment by yueqing-wolai** [comment]
Of course, I just use the basic function of markdown-it, you can add css or use  plugins of markdown-it to improve it.

**Comment by yueqing-wolai** [comment]
Seems like github has an OPEN API  to transform markdown to html. https://docs.github.com/en/rest/markdown?apiVersion=2022-11-28 And with this CSS https://github.com/sindresorhus/github-markdown-css, maybe we can make a github style markdown.

**Comment by yueqing-wolai** [comment]
image
Added code highlight, use github markdown style and add clipboard button. If you like it, I can make a PR

**Comment by wong2** [comment]
I'd prefer not using GitHub API, but a local markdown renderer. `github-markdown-css` is great, let's use it. You can add more commit to this PR.

**Comment by yueqing-wolai** [comment]
> I'd prefer not using GitHub API, a local markdown renderer will be faster and more reliable. `github-markdown-css` is great, let's use it. You can add more commit to this PR.

I'm using markdown-it to render it instead of Github API. Ok, I will add  it to this PR

**Comment by yueqing-wolai** [comment]
By the way, the code  button icon is not showed correctly. I changed the button icon in /node_modules/markdown-it-code-copy to this one, 	
```html
<button class="markdown-it-code-copy ${options.buttonClass}" data-clipboard-text="${content}" style="${options.buttonStyle}" title="Copy">
		<svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="w-4 h-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"></path><rect x="8" y="2" width="8" height="4" rx="1" ry="1"></rect></svg>
	</button>
```

**Comment by wong2** [comment]
Hi, I've merged part of your PR in https://github.com/wong2/chat-gpt-google-extension/pull/42

Need to figure out better ways for code highlighting or copy button afterwards. Thanks for your contribution!

**Pull request closed without merging**
